services:
  collector:
    image: otel/opentelemetry-collector

  redis:
    image: "redis:6.2-alpine"
    # Enable persistence
    command: "--save 60 500 --appendonly yes --appendfsync everysec"

  svix:
    image: svix/svix-server:v0.65
    ports:
      - 8071:8071
    environment:
      WAIT_FOR: "true"  # We want to wait for the default services
      SVIX_REDIS_DSN: "redis://redis:6379"
      SVIX_DB_DSN: "postgresql://postgres:postgres@postgres/postgres"
      SVIX_JWT_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3MzMwMDUsImV4cCI6MTk3NTA5MzAwNSwibmJmIjoxNjU5NzMzMDA1LCJpc3MiOiJzdml4LXNlcnZlciIsInN1YiI6Im9yZ18yM3JiOFlkR3FNVDBxSXpwZ0d3ZFhmSGlyTXUifQ.qVZYqK6s5Srk19LXwQj0TlulRD97jsJ73N2Ti6TJU68"
      JWT_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3MzMwMDUsImV4cCI6MTk3NTA5MzAwNSwibmJmIjoxNjU5NzMzMDA1LCJpc3MiOiJzdml4LXNlcnZlciIsInN1YiI6Im9yZ18yM3JiOFlkR3FNVDBxSXpwZ0d3ZFhmSGlyTXUifQ.qVZYqK6s5Srk19LXwQj0TlulRD97jsJ73N2Ti6TJU68"
      SVIX_JWT_SECRET: "8KjzRXrKkd9YFcNyqLSIY8JwiaCeRc6WK4UkMnSW"
      SVIX_LOG_LEVEL: "trace"

  postgres:
    image: postgres:13.4
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ledger" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    healthcheck:
      test: curl -s -f -k http://127.0.0.1:9644/metrics >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 9092:9092
      - 29092:29092
      - 9644:9644

  redpanda-ui:
    image: docker.redpanda.com/vectorized/console:master-0a8fce8
    ports:
      - 8081:8080
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      KAFKA_BROKERS: redpanda:29092

  webhooks:
    command: reflex -r '\.go' -s -- sh -c "go run ./ server"
    build:
      target: dev
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/_healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .:/app
    ports:
      - 8080:8080
    environment:
      STORAGE_MONGO_CONN_STRING: "mongodb://admin:admin@mongo:27017/"
      KAFKA_TOPIC: "default"
      KAFKA_BROKERS: "redpanda:29092"
      SVIX_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3MzMwMDUsImV4cCI6MTk3NTA5MzAwNSwibmJmIjoxNjU5NzMzMDA1LCJpc3MiOiJzdml4LXNlcnZlciIsInN1YiI6Im9yZ18yM3JiOFlkR3FNVDBxSXpwZ0d3ZFhmSGlyTXUifQ.qVZYqK6s5Srk19LXwQj0TlulRD97jsJ73N2Ti6TJU68"
      SVIX_SERVER_URL: "http://svix:8071"
      SVIX_ORGANIZATION_NAME: "webhooks"

  worker:
    command: reflex -r '\.go' -s -- sh -c "go run ./ worker"
    build:
      target: dev
    volumes:
      - .:/app
    environment:
      STORAGE_MONGO_CONN_STRING: "mongodb://admin:admin@mongo:27017/"
      KAFKA_TOPIC: "default"
      KAFKA_BROKERS: "redpanda:29092"
      SVIX_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTk3MzMwMDUsImV4cCI6MTk3NTA5MzAwNSwibmJmIjoxNjU5NzMzMDA1LCJpc3MiOiJzdml4LXNlcnZlciIsInN1YiI6Im9yZ18yM3JiOFlkR3FNVDBxSXpwZ0d3ZFhmSGlyTXUifQ.qVZYqK6s5Srk19LXwQj0TlulRD97jsJ73N2Ti6TJU68"
      SVIX_SERVER_URL: "http://svix:8071"
      SVIX_ORGANIZATION_NAME: "webhooks"
