---
apiVersion: garden.io/v1
kind: Project
name: stack

variables:
  cluster-name: formance

environments:
  - name: dev

providers:
  - name: kubernetes
    environments: ["dev"]
    setupIngressController: false
    context: k3d-formance
    buildMode: kaniko
    kaniko:
      extraFlags: # TODO: Make optional registries flag
      - --registry-mirror=registry-docker-io:5000
      - --insecure-registry=registry-docker-io:5000
      - --force
      - --snapshotMode=redo
      - --use-new-run
    deploymentRegistry:
      hostname: k3d-registry.host.k3d.internal
      insecure: true
      port: 12345
