version: '3'

vars:
  COMPONENT:
    sh: cat go.mod |head -1|cut -d \  -f2|cut -d / -f 3

tasks:
  lint:
    cmds:
    - golangci-lint run -v --fix
  build:
    cmds:
    - go build
  build-image:
    cmds:
    - docker build -t github.com/numary/{{.COMPONENT}} .
  run-image:
    deps:
    - build-image
    cmds:
    - docker run --rm github.com/numary/{{.COMPONENT}}
  generate-client:
  - >
    docker run --rm 
    -w /local 
    -v ${PWD}:/local 
    openapitools/openapi-generator-cli:latest generate 
    -i swagger.yaml 
    -g go 
    -o ./pkg/client 
    --git-user-id=numary 
    --git-repo-id=auth 
    -p packageVersion=latest 
    -p isGoSubmodule=true 
    -p packageName=authclient
