version: '3'

vars:
  COMPONENT:
    sh: cat go.mod |head -1|cut -d \  -f2|cut -d / -f 3

tasks:
  lint:
    cmds:
    - golangci-lint run -v --fix
  tests:
    cmds:
    - go test ./...
  build:
    cmds:
    - go build
  build-image:
    cmds:
    - docker build -t github.com/numary/{{.COMPONENT}} .
  run-image:
    deps:
    - build-image
    cmds:
    - docker run --rm github.com/numary/{{.COMPONENT}}
  generate-client:
  - >
    docker run --rm 
    -w /local 
    -v ${PWD}:/local 
    openapitools/openapi-generator-cli:latest generate 
    -i swagger.yaml 
    -g go 
    -o ./authclient 
    --git-user-id=numary 
    --git-repo-id=auth 
    -p packageVersion=latest 
    -p isGoSubmodule=true 
    -p packageName=authclient
  create-demo-client:
    vars:
      CLIENT_ID:
        sh: >
          curl -X POST 'http://localhost:8080/clients' 
          -H 'Content-Type: application/json' 
          -d '{"public": true, "name": "demo", "postLogoutRedirectUris": ["http://localhost:3000/"], "redirectUris": ["http://localhost:3000/auth-callback"]}'|jq -r .data.id
    preconditions:
    - sh: '[ "{{.CLIENT_ID}}" != "null" ]'
    cmds:
    - |
      echo export const REACT_APP_CLIENT_ID=\'{{.CLIENT_ID}}\' > demo/src/config.js
