---
version: "3"

vars:
  version: v1.0.{{now | date "20060102"}}
  openapiGeneratorVersion: v6.4.0

tasks:
  sdk:build:
    desc: Build the SDK
    cmds:
      - npm install
      - npm run build
      - cat <<< $(jq '.info.version = "{{.version}}"' build/generate.json) > build/generate.json

  sdk:generate:
    internal: true
    cmds:
      - rm -rf ../sdks/{{.target}}
      - >
        docker run --rm -w /local -v ${PWD}/..:/local openapitools/openapi-generator-cli:{{.openapiGeneratorVersion}} generate
        -i ./openapi/build/generate.json
        -g {{ (split "-" .target)._0 }}
        -c ./openapi/configs/{{.target}}.yaml
        -o ./sdks/{{.target}}
        --git-user-id=formancehq
        --git-repo-id=formance-sdk-{{.target}}
        -p packageVersion={{.version}}
        -p apiVersion={{.version}}

  sdk:test:
    internal: true
    vars:
      testingImage:
        sh: docker build -q -f tests/{{.target}}/Dockerfile ..
    cmds:
    - docker run --rm -e SDK_VERSION={{.version}} {{.testingImage}}

  sdk:generate:typescript-node:
    cmds:
    - task: sdk:generate
      vars:
        target: typescript-node

  sdk:generate:php:
    cmds:
    - task: sdk:generate
      vars:
        target: php

  sdk:generate:java:
    cmds:
    - task: sdk:generate
      vars:
        target: java

  sdk:generate:python:
    cmds:
    - task: sdk:generate
      vars:
        target: python

  sdk:generate:go:
    cmds:
    - task: sdk:generate
      vars:
        target: go

  sdk:test:typescript-node:
    cmds:
    - task: sdk:test
      vars:
        target: typescript-node

  sdk:test:php:
    cmds:
    - task: sdk:test
      vars:
        target: php

  sdk:test:java:
    cmds:
    - task: sdk:test
      vars:
        target: java

  sdk:test:python:
    cmds:
    - task: sdk:test
      vars:
        target: python

  sdk:test:go:
    cmds:
    - task: sdk:test
      vars:
        target: go

  sdk:publish:go:
    cmds:
    - echo "Nothing to do"

  sdk:publish:java:
    cmds:
    - mvn deploy

  sdk:publish:php:
    cmds:
    - echo "Nothing to do"

  sdk:publish:python:
    cmds:
    - echo "Push on PyPi"

  sdk:publish:typescript-node:
    cmds:
    - echo "Push on npmjs"

  sdk:generate:all:
    desc: Generate all client code
    deps:
    - task: sdk:generate:typescript-node
    - task: sdk:generate:python
    - task: sdk:generate:java
    - task: sdk:generate:php
    - task: sdk:generate:go
