openapi: 3.0.3
info:
  title: Webhooks
  version: 0.0.0
paths:
  /_healthcheck:
    get:
      summary: Health check of the server.
      operationId: healthCheck
      tags:
        - Health check
      responses:
        "200":
          description: The server is healthy.
          content: {}

  /configs:
    get:
      summary: Get all configs, sorted by modification date descending.
      operationId: getAllConfigs
      tags:
        - Configs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - cursor
                properties:
                  cursor:
                    allOf:
                      - $ref: '#/components/schemas/Cursor'
                      - type: object
                        properties:
                          data:
                            type: array
                            items:
                              $ref: '#/components/schemas/ConfigInserted'
                        required:
                          - data

    post:
      summary: Insert a new config.
      operationId: insertOneConfig
      tags:
        - Configs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - cursor
                properties:
                  cursor:
                    allOf:
                      - $ref: '#/components/schemas/Cursor'
                      - type: object
                        properties:
                          data:
                            type: array
                            items:
                              $ref: '#/components/schemas/ConfigInserted'
                        required:
                          - data
        "400":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: endpoints should be valid urls

    delete:
      summary: Delete one config by ID.
      operationId: deleteOneConfig
      tags:
        - Configs
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

  /configs/toggle:
    post:
      summary: Toggle on/off config activation by ID.
      operationId: toggleOneConfig
      tags:
        - Configs
      parameters:
        - name: id
          in: path
          description: Config ID
          required: true
          schema:
            type: string
            example: 4997257d-dfb6-445b-929c-cbe2ab182818
      responses:
        "200":
          description: OK
          content: {}

components:
  schemas:
    Config:
      type: object
      additionalProperties:
        type: object
      example: {"endpoint":"https://www.site.com","eventTypes":["TYPE1", "TYPE2"]}
    ConfigInserted:
      type: object
      additionalProperties:
        type: object
      example: {"endpoint":"https://www.site.com","eventTypes":["TYPE1", "TYPE2"],"active":true,"createdAt":"2022-07-20T07:31:40.9Z","modifiedAt":"2022-07-20T07:32:00Z"}
    Cursor:
      type: object
      properties:
        has_more:
          type: boolean
          example: false
