tests:
  - name: invalid JSON
    target_processors: '/pipeline/processors'
    input_batch:
      - content: 'not JSON'

  - name: missing organization
    target_processors: '/pipeline/processors'
    input_batch:
      - content: '{}'

  - name: organization already in metadata
    target_processors: '/pipeline/processors'
    input_batch:
      - content: '{}'
        metadata:
          organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763
    output_batches:
      -
        - json_equals: '{}'
          metadata_equals:
            organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763

  - name: organization already in metadata, but with capital first letter
    target_processors: '/pipeline/processors'
    input_batch:
      - content: '{}'
        metadata:
          Organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763
    output_batches:
      -
        - json_equals: '{}'
          metadata_equals:
            organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763

  - name: organization already in metadata, but in Message-Metadata key
    target_processors: '/pipeline/processors'
    input_batch:
      - content: '{}'
        metadata:
          Message-Metadata: '{"organization":"ad4b13ce-d9a7-4212-ad71-8a02dee11763"}'
    output_batches:
      -
        - json_equals: '{}'
          metadata_equals:
            organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763

  - name: created organization
    target_processors: '/pipeline/processors'
    input_batch:
      - content: >-
          {
            "payload":{
              "organization":{
                "id":"ad4b13ce-d9a7-4212-ad71-8a02dee11763"
              }
            },
            "type":"CREATED_ORGANIZATION"
          }
    output_batches:
      -
        - json_equals: >-
            {
              "payload":{
                "organization":{
                  "id":"ad4b13ce-d9a7-4212-ad71-8a02dee11763"
                }
              },
              "type":"CREATED_ORGANIZATION"
            }
          metadata_equals:
            organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763

  - name: deleted organization
    target_processors: '/pipeline/processors'
    input_batch:
      - content: >-
          {
            "id":"ad4b13ce-d9a7-4212-ad71-8a02dee11763",
            "type":"DELETED_ORGANIZATION"
          }
    output_batches:
      -
        - json_equals: >-
            {
              "id":"ad4b13ce-d9a7-4212-ad71-8a02dee11763",
              "type":"DELETED_ORGANIZATION"
            }
          metadata_equals:
            organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763

  - name: Svix app created
    target_processors: '/output/switch/cases/0/output/processors'
    input_batch:
      - content: >-
          {
            "payload":{
              "organization":{
                "id":"ad4b13ce-d9a7-4212-ad71-8a02dee11763",
                "name": "test"
              }
            },
            "type":"CREATED_ORGANIZATION"
          }
        metadata:
          organization: ad4b13ce-d9a7-4212-ad71-8a02dee11763
    output_batches:
      -
        - json_equals: >-
            {
              "name": "test (ad4b13ce-d9a7-4212-ad71-8a02dee11763)",
              "rateLimit": 1000,
              "uid": "ad4b13ce-d9a7-4212-ad71-8a02dee11763"
            }
