http:
  enabled: true
  address: 0.0.0.0:4195

tracer:
  jaeger:
    agent_address: "${JAEGER_COLLECTOR}"
    service_name: webhooks-ingest

input:
  broker:
    inputs:
    - kafka:
        consumer_group: webhooks
        addresses:
        - ${KAFKA_ADDRESS}
        topics:
        - ${KAFKA_TOPIC}
        client_id: webhooks-benthos-ingest
        tls:
          enabled: ${KAFKA_TLS_ENABLED}
        sasl:
          enabled: ${KAFKA_SASL_ENABLED}
          mechanism: ${KAFKA_SASL_MECHANISM}
          user: ${KAFKA_SASL_USER}
          password: ${KAFKA_SASL_PASSWORD}

pipeline:
  processors:
    - log:
        level: INFO
        message: "LOG-BEFORE"
        fields_mapping: root = this

    - json_schema:
        schema: '{"type": "object"}'
    - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: root = deleted()

    - bloblang: |
        root = this
        meta organization = if (root.payload.organization.id) != null).catch(false) {
          root.payload.organization.id
        }
    - bloblang: |
        root = this
        meta organization = if (meta("Message-Metadata") != null).catch(false) {
          meta("Message-Metadata").parse_json().organization
        }
    - bloblang: |
        root = this
        meta organization = if (meta("Organization") != null).catch(false) {
          meta("Organization")
        }
    - bloblang: |
        root = this
        root.meta = meta()
        _organization = meta("organization")
    - catch:
        - log:
            level: ERROR
            message: 'Skipping message because missing "organization" metadata'
        - bloblang: root = deleted()
    - bloblang: |
        root = this
        _type = this.type
    - catch:
        - log:
            level: ERROR
            message: 'Skipping message because missing "type" key'
        - bloblang: root = deleted()

    - log:
        level: INFO
        message: "LOG-AFTER"
        fields_mapping: root = this

output:
  switch:
    cases:
      - check: this.type == "CREATED_ORGANIZATION"
        output:
          http_client:
            url: http://webhooks:80/organizations
            verb: POST
            headers:
              Content-Type: application/json

      - check: this.type == "DELETED_ORGANIZATION"
        output:
          http_client:
            url: http://webhooks:80/organizations
            verb: DELETE
            headers:
              Content-Type: application/json

      - output:
          http_client:
            url: http://webhooks:80/trash
            verb: POST
            headers:
              Content-Type: application/json
