http:
  enabled: true
  address: 0.0.0.0:4195

tracer:
  jaeger:
    agent_address: "${JAEGER_COLLECTOR}"
    service_name: webhooks-ingest

input:
  broker:
    inputs:
    - http_server:
        path: /
        allowed_verbs:
        - POST
    - kafka:
        consumer_group: webhooks
        addresses:
        - ${KAFKA_ADDRESS}
        topics:
        - ${KAFKA_TOPIC}
        client_id: webhooks-benthos-ingest
        tls:
          enabled: ${KAFKA_TLS_ENABLED}
        sasl:
          enabled: ${KAFKA_SASL_ENABLED}
          mechanism: ${KAFKA_SASL_MECHANISM}
          user: ${KAFKA_SASL_USER}
          password: ${KAFKA_SASL_PASSWORD}

pipeline:
  processors:
    - json_schema:
        schema: '{"type": "object"}'
    - catch:
        - log:
            level: ERROR
            message: "Schema validation failed due to: ${!error()}"
        - bloblang: root = deleted()
    - log:
        level: DEBUG
        message: log
        fields_mapping: |
          root.message = this
          root.meta = meta()

output:
  broker:
    outputs:
      - stdout: {}
      - http_client:
          url: http://webhooks:80/_ingest
          verb: POST
          headers:
            Content-Type: application/json
