version: '3'

vars:
  BINARY_NAME: payments
  PKG: ./...
  FAILFAST: -failfast
  TIMEOUT: 10m

tasks:
  default:
    cmds:
      - task: lint
      - task: tests

  lint:
    cmds:
      - golangci-lint run --fix

  tests:
    cmds:
    - mkdir -p ./coverdir
    - go test {{.FAILFAST}} -cover {{.PKG}} -coverpkg {{.PKG}} -covermode atomic -timeout {{.TIMEOUT}} -test.gocoverdir=$(pwd)/coverdir

  build:
    cmds:
    - go build -o {{.BINARY_NAME}}

  install:
    cmds:
    - go install -o {{.BINARY_NAME}}

  clean:
    cmds:
    - rm -f {{.BINARY_NAME}} {{.COVERAGE_FILE}}
