openapi: 3.0.3
info:
  contact: {}
  title: Auth API
  version: AUTH_VERSION
servers:
- description: Production server
  url: "https://{organization}.o.numary.cloud/auth"
  variables:
    organization:
      default: ""
      description: The organization on which the auth server is located
paths:
  /clients:
    get:
      operationId: listClients
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListClientsResponse'
          description: List of clients
      summary: List clients
    post:
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClientRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateClientResponse'
          description: Client created
      summary: Create client
  /clients/{clientId}:
    delete:
      operationId: deleteClient
      parameters:
      - description: Client ID
        explode: false
        in: path
        name: clientId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Client deleted
      summary: Delete client
    get:
      operationId: readClient
      parameters:
      - description: Client ID
        explode: false
        in: path
        name: clientId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadClientResponse'
          description: Retrieved client
      summary: Read client
    put:
      operationId: updateClient
      parameters:
      - description: Client ID
        explode: false
        in: path
        name: clientId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateClientRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateClientResponse'
          description: Updated client
      summary: Update client
  /clients/{clientId}/scopes/{scopeId}:
    delete:
      operationId: deleteScopeFromClient
      parameters:
      - description: Client ID
        explode: false
        in: path
        name: clientId
        required: true
        schema:
          type: string
        style: simple
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Scope deleted from client
      summary: Delete scope from client
    put:
      operationId: addScopeToClient
      parameters:
      - description: Client ID
        explode: false
        in: path
        name: clientId
        required: true
        schema:
          type: string
        style: simple
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Scope added to client
      summary: Add scope to client
  /scopes:
    get:
      description: List Scopes
      operationId: listScopes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListScopesResponse'
          description: List of scopes
      summary: List scopes
    post:
      description: Create scope
      operationId: createScope
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateScopeRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateScopeResponse'
          description: Created scope
      summary: Create scope
  /scopes/{scopeId}:
    delete:
      description: Delete scope
      operationId: deleteScope
      parameters:
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Scope deleted
      summary: Delete scope
    get:
      description: Read scope
      operationId: readScope
      parameters:
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadScopeResponse'
          description: Retrieved scope
      summary: Read scope
    put:
      description: Update scope
      operationId: updateScope
      parameters:
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateScopeRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateScopeResponse'
          description: Updated scope
      summary: Update scope
  /scopes/{scopeId}/transient/{transientScopeId}:
    delete:
      description: Delete a transient scope from a scope
      operationId: deleteTransientScope
      parameters:
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      - description: Transient scope ID
        explode: false
        in: path
        name: transientScopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Transient scope deleted
      summary: Delete a transient scope from a scope
    put:
      description: Add a transient scope to a scope
      operationId: addTransientScope
      parameters:
      - description: Scope ID
        explode: false
        in: path
        name: scopeId
        required: true
        schema:
          type: string
        style: simple
      - description: Transient scope ID
        explode: false
        in: path
        name: transientScopeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Scope added
      summary: Add a transient scope to a scope
components:
  schemas:
    ClientOptions:
      example:
        public: true
        postLogoutRedirectUris:
        - postLogoutRedirectUris
        - postLogoutRedirectUris
        name: name
        description: description
        redirectUris:
        - redirectUris
        - redirectUris
      properties:
        public:
          type: boolean
        redirectUris:
          items:
            type: string
          type: array
        description:
          type: string
        name:
          type: string
        postLogoutRedirectUris:
          items:
            type: string
          type: array
      required:
      - name
      type: object
    Client:
      allOf:
      - $ref: '#/components/schemas/ClientOptions'
      - $ref: '#/components/schemas/Client_allOf'
    ScopeOptions:
      example:
        label: label
      properties:
        label:
          type: string
      required:
      - label
      type: object
    Scope:
      allOf:
      - $ref: '#/components/schemas/ScopeOptions'
      - $ref: '#/components/schemas/Scope_allOf'
    CreateClientRequest:
      $ref: '#/components/schemas/ClientOptions'
    CreateClientResponse:
      example:
        data: null
      properties:
        data:
          $ref: '#/components/schemas/Client'
      type: object
    ListClientsResponse:
      example:
        data:
        - null
        - null
      properties:
        data:
          items:
            $ref: '#/components/schemas/Client'
          type: array
      type: object
    UpdateClientRequest:
      $ref: '#/components/schemas/ClientOptions'
    UpdateClientResponse:
      $ref: '#/components/schemas/CreateClientResponse'
    ReadClientResponse:
      example:
        data: null
      properties:
        data:
          $ref: '#/components/schemas/Client'
      type: object
    ListScopesResponse:
      example:
        data:
        - null
        - null
      properties:
        data:
          items:
            $ref: '#/components/schemas/Scope'
          type: array
      type: object
    CreateScopeRequest:
      $ref: '#/components/schemas/ScopeOptions'
    CreateScopeResponse:
      example:
        data: null
      properties:
        data:
          $ref: '#/components/schemas/Scope'
      type: object
    ReadScopeResponse:
      $ref: '#/components/schemas/CreateScopeResponse'
    UpdateScopeRequest:
      $ref: '#/components/schemas/ClientOptions'
    UpdateScopeResponse:
      $ref: '#/components/schemas/CreateScopeResponse'
    Client_allOf:
      properties:
        id:
          type: string
        scopes:
          items:
            type: string
          type: array
      required:
      - id
      type: object
    Scope_allOf:
      properties:
        id:
          type: string
        transient:
          items:
            type: string
          type: array
      required:
      - id
      type: object
