version: '3'

env:
  LOG_LEVEL: "debug"

vars:
  SERVICE: "wallets"
  APP_VERSION: "develop"
  APP_SHA: "ksjfsldkf"

  PKG: "./..."
  FAILFAST: "-failfast"
  TIMEOUT: "1m"
  RUN: "''"
  VERBOSE: "false"

tasks:
  default:
    cmds:
      - task: lint
      - task: tests

  lint:
    cmds:
      - golangci-lint run --fix {{if eq .VERBOSE "true"}}-v{{end}}

  tests:
    cmds:
      - mkdir -p ./coverdir
      - go test {{if eq .VERBOSE "true"}}-v{{end}} -race -cover {{.PKG}} -coverpkg {{.PKG}} -test.gocoverdir=$(pwd)/coverdir
