version: '3'

vars:
  COMPONENT:
    sh: cat go.mod |head -1|cut -d \  -f2|cut -d / -f 3

tasks:
  tests:
    cmds:
    - mkdir -p ./coverdir
    - go test -cover ./... -coverpkg ./... -covermode atomic ./... -test.gocoverdir=$(pwd)/coverdir

  lint:
    cmds:
    - golangci-lint run --fix

  build:
    cmds:
    - go build

  build-image:
    cmds:
    - docker build -t github.com/formancehq/{{.COMPONENT}} .

  run-image:
    deps:
    - build-image
    cmds:
    - docker run --rm github.com/formancehq/{{.COMPONENT}}
