# https://taskfile.dev
version: "3"

env:
  VERSION: v1.1.0

tasks:
  generate:
    internal: true
    cmds:
      - rm -rf ./../sdks/{{.TARGET}}
      - mkdir -p ./../sdks/{{.TARGET}}
      - cp -r ./templates/{{.TARGET}} ./../sdks/
      - yq -y -i '.{{.TARGET}}.version = "{{.VERSION}}"' ./../sdks/{{.TARGET}}/gen.yaml
      - speakeasy generate sdk -s ./../releases/versions/{{.VERSION}}/openapi.json -o ./../sdks/{{.TARGET}} -l {{.TARGET}}

  generate:local:
    desc: Generate all client code
    deps:
      - task: generate
        vars: {TARGET: "go", VERSION: "local"}

  generate:all:
    desc: Generate all client code
    deps:
      - task: generate
        vars: {TARGET: "go", VERSION: "{{.VERSION}}"}
      - task: generate
        vars: {TARGET: "java", VERSION: "{{.VERSION}}"}
      - task: generate
        vars: {TARGET: "php", VERSION: "{{.VERSION}}"}
      - task: generate
        vars: {TARGET: "python", VERSION: "{{.VERSION}}"}
      - task: generate
        vars: {TARGET: "typescript", VERSION: "{{.VERSION}}"}
