version: "3"

tasks:
  release:
    cmds:
      - task: build
      - for i in $(ls *.tgz); do helm push $i oci://ghcr.io/formancehq/helm; done

  build:
    cmds:
      - task: build:agent
      - task: build:operator
      - task: build:regions

  build:regions:
    dir: ./regions
    cmds:
      - helm dependencies update
      - helm dependencies build
      - helm package ./
      - mv regions-*.tgz ./../regions.tgz
  build:operator:
    cmds:
      - helm package ./operator
  build:agent:
    cmds:
      - helm package ./agent