# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [lint, tests]

  tests:
    cmds:
    - mkdir -p ./coverdir
    - go test -coverpkg ./... -covermode atomic ./...  -test.gocoverdir=$(pwd)/coverdir;

  lint:
    cmds:
      - golangci-lint run --fix
