---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}-cluster-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      annotations:
        ad.datadoghq.com/{{ .Values.serviceName }}.logs: '[{"source":"kubernetes","service":"{{ .Values.serviceName }}"}]'
      labels:
        app: {{ .Values.serviceName }}
        tags.datadoghq.com/{{ .Values.serviceName }}.service: "{{ .Values.serviceName }}"
    spec:
      serviceAccountName: {{ .Values.serviceName }}-cluster-service-account
      containers:
        - image: "{{ .Values.awsAccountId }}.{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.serviceName }}
          imagePullPolicy: Always
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: ENV
              value: {{ .Values.env }}
            - name: AUTH_BEARER_AUDIENCE_TEMPLATE
              value: {{.Values.auth.audienceTemplate}}
            - name: AUTH_BEARER_ENABLED
              value: "true"
            - name: AUTH_BEARER_INTROSPECT_URL
              value: {{.Values.auth.introspectUrl}}
          ports:
            - containerPort: 8080
              name: {{ .Values.serviceName }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi

