name: Default - Release
on:
  push:
    branches:
    - feat/sdk-testing-and-publish
    tags:
      - 'components/sdks/v*.*.*'

jobs:
  Sdk:
    name: 'Generate and publish sdks'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update SDKS
      run: |
        task openapi:sdk:build;
        [ "$(git diff)" == "" ] || {
          echo "OpenAPI spec computation give changes, please update SDKS before push code";
          git diff;
          exit 1;
        }

        task openapi:sdk:generate:all;
        [ "$(git diff)" == "" ] || {
          echo "OpenAPI code generation give changes, please update SDKS before push code";
          git diff;
          exit 1;
        }

        versionFromSpec=$(jq -r '.info.version' ./openapi/build/generate.json);
        versionFromTag=$(echo $GITHUB_REF_NAME | cut -d / -f 3);
        [ "$versionFromSpec" == "$versionFromTag" ] || {
          echo "Versions from spec and tag mismatch, please update SDKS before push code";
          exit 1;
        }
        task openapi:sdk:test:all;

        for sdk in $(ls sdks); do
          pushd sdks/$sdk;
          echo "Git init"
          git init;
          echo "Git init terminated"
          git remote add origin https://github.com/formancehq/formance-sdk-$sdk
          git checkout -b release/$versionFromSpec;
          git add -A;
          git commit -m "feat: Upgrade to version $versionFromSpec";
          git push -f origin release/$versionFromSpec;
          git tag $versionFromSpec;
          git push -f origin $versionFromSpec;
          popd;
        done

        task openapi:sdk:publish:all
